-- CustomerID inválido para PK (nulo o vacío)
SELECT CustomerID
FROM TXT_Customers
WHERE CustomerID IS NULL
   OR TRIM(CustomerID) = '';

;
INSERT INTO LOG_Ejecucion (
    script_name,
    start_time,
    end_time,
    status,
    rows_affected,
    message
)
VALUES (
    'Validar Formatos TXT_Customers.sql',
    datetime('now','-60 seconds'),   -- o reemplazalo por una variable si tenés
    datetime('now'),
    'SUCCESS',
    0,
    'No se encontraron inconsistencias de los tipos de datos'
);
